language: python
sudo: false
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"

# command to install dependencies
install:
  - python setup.py build sdist
  - pip install -r requirements.txt
# command to run tests
script: nosetests --verbosity 2
